export default{
    GET_ALL_EMPLOYEES: "GET_ALL_EMPLOYEES",
    GET_EMPLOYEES: "GET_EMPLOYEES",
    GET_SINGLE_EMPLOYEE: "GET_SINGLE_EMPLOYEE",
    ADD_EMPLOYEES: 'ADD_EMPLOYEES',
    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
    UPDATE_EMPOYEE: 'UPDATE_EMPLOYEE',
    GET_USERS: 'GET_USERS',
}